service-catalog-ui:
  enabled: false

global:
  domainName: "kyma.example.com"
  containerRegistry:
    path: docker.io/eagledai # I078212
  images:
    service_binding_usage_controller:
      name: "service-binding-usage-controller"
      version: "75da62ce"
  istio:
    gateway:
      name: kyma-gateway
  ingress:
    domainName: "TBD"
