rbac:
  create: true
  pspEnabled: true

networkPolicy:
  enabled: false

serviceAccount:
  create: true
  name:
  annotations: {}

# enable tracing for debug, need install jaeger and specify right jaeger_agent_host
tracing:
  jaegerAgentHost:

fluent-bit:
  enabled: true

loki:
  enabled: true

global:
  containerRegistry:
    path: docker.io # I078212
  images:
    fluent_bit:
      name: fluent-bit
      version: 1.8.12-780c4842
      directory: eagledai # I078212
    loki:
      name: loki
      version: 2.2.1-2696e5d5
      directory: eagledai # I078212
  kymaRuntime:
    adminGroup: runtimeAdmin
    operatorGroup: runtimeOperator
    developerGroup: runtimeDeveloper
    namespaceAdminGroup: runtimeNamespaceAdmin
  istio:
    gateway:
      name: kyma-gateway
      namespace: kyma-system
  tracing:
    enabled: true
  highPriorityClassName: "kyma-system-priority"
